language: php
php:
  - 7.1
  - 7.2
  - 7.3
env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
matrix:
  include:
    - php: 7.3
      env: WP_VERSION=trunk WP_MULTISITE=0
    - php: 7.3
      env: WP_VERSION=trunk WP_MULTISITE=1
services:
  - mysql
install:
  - composer install
  - bash tests/install-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION
script:
  # 32656 tests are related to the pre_*_event filters which we're using already
  - vendor/bin/phpunit --exclude-group 32656
notifications:
    email: false
