kind: pipeline
type: docker
name: build
steps:
- name: build
  image: rockylinux
  pull: if-not-exists # always never
  environment:
    RSYNC_PORT:
      from_secret: RSYNC_PORT
    RSYNC_HOST:
      from_secret: RSYNC_HOST
    RSYNC_USER:
      from_secret: RSYNC_USER
    RSYNC_PASS:
      from_secret: RSYNC_PASS
  commands:
	- dnf install rsync -y
    - export RSYNC_PASSWORD=$RSYNC_PASS
    - cd /builds/litepress/litepress.cn/wp-content/
    - rsync -rapogz --port=$RSYNC_PORT --chown=www:www --chmod=775 --delete --include "plugins/" --include "themes/" --include "mu-plugins/" --exclude "/*" . $RSYNC_USER@$RSYNC_HOST::$RSYNC_USER/wp-content/
trigger:
  branch:
  - main